
// This file has been generated by the GUI designer. Do not modify.
namespace Launcher
{
	public partial class SplashScreen
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Image image2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Launcher.SplashScreen
			this.Name = "Launcher.SplashScreen";
			this.Title = global::Mono.Unix.Catalog.GetString ("SplashScreen");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Decorated = false;
			this.Role = "";
			// Container child Launcher.SplashScreen.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Xalign = 0f;
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Launcher.image.SplashScreen.gif");
			this.fixed1.Add (this.image2);
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 667;
			this.DefaultHeight = 477;
			this.Show ();
		}
	}
}
